name: Uptime Monitor

on:
  schedule:
    # Run the script every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  check_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Run monitoring script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SERVICE_URL: ${{ secrets.SERVICE_URL }}
      run: python monitor_web_bot.py
